// Fake events for testing. Replace with the events teammate's real data later.
export const MOCK_EVENTS = [
  {
    event_id: 'evt_101',
    zip_code: '33174',
    business_name: 'Corner Coffee Roasters',
    is_promoted: true,
    title: 'New Neighbor Acoustic Night',
    category: 'cafe',
    date_time: 'Fri • 7:00 PM',
    new_mover_perk: 'Free cold brew with RSVP',
    attendees_count: 24,
    lat: 25.7617,
    lng: -80.3659,
  },
  {
    event_id: 'evt_102',
    zip_code: '33165',
    business_name: 'Neighborhood Run Club',
    is_promoted: false,
    title: 'Saturday Morning 5K',
    category: 'fitness',
    date_time: 'Sat • 8:00 AM',
    new_mover_perk: null,
    attendees_count: 15,
    lat: 25.7449,
    lng: -80.3833,
  },
  {
    event_id: 'evt_103',
    zip_code: '33155',
    business_name: 'Weekend Makers Market',
    is_promoted: true,
    title: 'Local Pop-up Market',
    category: 'market',
    date_time: 'Sun • 11:00 AM',
    new_mover_perk: '10% off for new residents',
    attendees_count: 40,
    lat: 25.7390,
    lng: -80.3420,
  },
];
